on:
  push:
    branches:
      - "dev"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initiate
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: opsel-agent
          path: opsel
